- hosts: webservers
  become: yes
  tasks:
    - name: update
      apt: update_cache=yes

    - name: Install nginx
      apt: 
        name: nginx
        state: present
     
    - name: Start Nginx Service
      service:
        name: nginx
        state: started

    - name: clone website
      ansible.builtin.git:
        repo: https://github.com/ArchLinuxChad/dillonking.xyz
        dest: /var/www/website

    - name: copy index.html to /var/www/html
      copy:
        remote_src: yes
        src: /var/www/website/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: o=r,g=r,u=rwx

     - name: install ufw
       apt:
         name: ufw
	 sate: present
     - name: start ufw
         service:
           name: ufw
           state: started
     - name: configure ufw
       cmd: ufw default deny incoming && ufw default allow outgoing && ufw allow 80,443,22/tcp
      
